version: '3.8'

services:
  php:
    container_name: php
    build:
      context: ./docker
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/game

  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./app:/app
    command: sh -c "composer install --no-plugins --no-scripts && composer install"
    depends_on:
      - php
